### ISSUE TITLE
throwing errors in plugin_net.log

### ISSUE THREAD

**Issue by liljenstolpe** [Metaswitch/calico-docker-prototype#14]
I'm seeing nothing but the following in log/plugin_net.log on the plugin host (core-01)

2015-01-17 01:16:29,731 [ERROR] __main__ 293: Got an error
Traceback (most recent call last):
  File "/opt/scripts/plugin.py", line 277, in do_network_api
    data   = rep_socket.recv()
  File "socket.pyx", line 622, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5560)
  File "socket.pyx", line 656, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5380)
  File "socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1758)
  File "checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5960)
Again: Resource temporarily unavailable
2015-01-17 01:16:29,732 [DEBUG] __main__ 299: Build data to publish
2015-01-17 01:16:34,737 [ERROR] __main__ 293: Got an error
Traceback (most recent call last):
  File "/opt/scripts/plugin.py", line 277, in do_network_api
    data   = rep_socket.recv()
  File "socket.pyx", line 622, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5560)
  File "socket.pyx", line 656, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5380)
  File "socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1758)
  File "checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5960)
Again: Resource temporarily unavailable
2015-01-17 01:16:34,738 [DEBUG] __main__ 299: Build data to publish
2015-01-17 01:16:39,744 [ERROR] __main__ 293: Got an error
Traceback (most recent call last):
  File "/opt/scripts/plugin.py", line 277, in do_network_api
    data   = rep_socket.recv()
  File "socket.pyx", line 622, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5560)
  File "socket.pyx", line 656, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5380)
  File "socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1758)
  File "checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5960)
Again: Resource temporarily unavailable
2015-01-17 01:16:39,744 [DEBUG] __main__ 299: Build data to publish
2015-01-17 01:16:44,751 [ERROR] __main__ 293: Got an error
Traceback (most recent call last):
  File "/opt/scripts/plugin.py", line 277, in do_network_api
    data   = rep_socket.recv()
  File "socket.pyx", line 622, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5560)
  File "socket.pyx", line 656, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5380)
  File "socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1758)
  File "checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5960)
Again: Resource temporarily unavailable
2015-01-17 01:16:44,751 [DEBUG] __main__ 299: Build data to publish
2015-01-17 01:16:49,757 [ERROR] __main__ 293: Got an error
Traceback (most recent call last):

**Comment by Lukasa** [comment]
This is the result of an overbroad bit of exception handling in the plugin [here](https://github.com/Metaswitch/calico-docker-prototype/blob/master/plugin/plugin.py#L291-L294). EAGAIN is exactly the error we expect to see on a timeout. Really there should be a proper `except` block here that handles this case without spamming the logs.

**Comment by neiljerram** [comment]
Agreed - I.e. We believe these are benign.

I was seeing these in my work yesterday evening, and they didn't cause any real problem.

------------------

**Comment by plwhite** [comment]
This was benign. We catch an exception that means "no data received", and log it rather than suppress it. Fixed in PR #15.
